services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redis_commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis_commander
    environment:
      REDIS_HOSTS: "local:redis:6379"
      ADDRESS: "0.0.0.0"
      # REDIS_HOSTS: "ext:192.168.100.129:6379"
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped